config/routes.rb
Rails.application.routes.draw do
  resources :waters

  get 'say/hello'

  get 'say/goodbye'

end

app/models/water.rb
class Water < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
	@time = Time.now
  end

  def goodbye
  end
end

app/controllers/waters_controller.rb
class WatersController < ApplicationController
  before_action :set_water, only: [:show, :edit, :update, :destroy]

  # GET /waters
  # GET /waters.json
  def index
    @waters = Water.all
  end

  # GET /waters/1
  # GET /waters/1.json
  def show
  end

  # GET /waters/new
  def new
    @water = Water.new
  end

  # GET /waters/1/edit
  def edit
  end

  # POST /waters
  # POST /waters.json
  def create
    @water = Water.new(water_params)

    respond_to do |format|
      if @water.save
        format.html { redirect_to @water, notice: 'Water was successfully created.' }
        format.json { render :show, status: :created, location: @water }
      else
        format.html { render :new }
        format.json { render json: @water.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waters/1
  # PATCH/PUT /waters/1.json
  def update
    respond_to do |format|
      if @water.update(water_params)
        format.html { redirect_to @water, notice: 'Water was successfully updated.' }
        format.json { render :show, status: :ok, location: @water }
      else
        format.html { render :edit }
        format.json { render json: @water.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waters/1
  # DELETE /waters/1.json
  def destroy
    @water.destroy
    respond_to do |format|
      format.html { redirect_to waters_url, notice: 'Water was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water
      @water = Water.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def water_params
      params.require(:water).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/waters_helper.rb
module WatersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
Enter HTML
!!!
%html
  %head
    %title Demo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/say/goodbye.html.haml
%h1 Goodbye!
%p It ws nice having you here 

%p
  Time to say
  \#{link_to "Hello" , say_hello_path} again.

app/views/say/hello.html.haml
%h1 Hello from Rails!
%p Look what we can do!

%p it is now #{@time}

%p
  Time to say
  \#{link_to "Goodbye" , say_goodbye_path}!

app/views/waters/_form.html.haml
= form_for(@waters) do |f|
  - if @water.errors.any?
    #error_explanation
      %h2
        = pluralize (@water.errors.count, "error")
        prohibited this edit from being save:
      %ul
        - @water.errors.full_messages.each do|msg|
          %li= msg
  .field
    - f.label :title
    %br
      - f.text_field :title
  %div
    class= "actions">
    \#{f.submit}

app/views/waters/edit.html.haml
%h1 Editing water

= render 'form'

= link_to 'Show', @water
\|
= link_to 'Back', waters_path

app/views/waters/index.html.haml
%h1 Listing waters

%table
  %thead
    %tr
      %th  title
      %th Description
      %th
      %th
      %th
      
  %tbody
    - @waters.each do |water|
      %tr
        %td= water. title
        %td= water.description
        %td= link_to 'Show', water
        %td= link_to 'Edit', edit_water_path(water)
        %td= link_to 'Destroy', water, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Water', new_water_path

app/views/waters/new.html.haml
%h1 New water

= render 'form'

= link_to 'Back', waters_path

app/views/waters/show.html.haml
%p#notice= notice

%p
  %b  title:
  = @water. title
%p
  %b Description:
  = @water.description

= link_to 'Edit', edit_water_path(@water)
\|
= link_to 'Back', waters_path